language: python

matrix:
  include:
    - python: pypy
      dist: xenial
      sudo: true
      env: TOXENV=pypy
    - python: 3.5
      dist: xenial
      sudo: true
      env: TOXENV=py35
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38
    - python: 2.7
      dist: xenial
      sudo: true
      env: TOXENV=py27
      arch: ppc64le  
    - python: 3.6
      dist: xenial
      sudo: true
      arch: ppc64le
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
      arch: ppc64le
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=py38
      arch: ppc64le
    - python: 3.8
      dist: xenial
      sudo: true
      env: TOXENV=cover
      arch: ppc64le

env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=cover
  - TOXENV=flake8

install:
  - travis_retry pip install tox==3.13.2

script:
  - travis_retry tox

git:
  depth: 1

notifications:
  email:
    - brian@kyr.us
